defaults:
  - models: TextCNN
  - override hydra/job_logging: disabled
  - _self_


n_epoch: 10
saving_path: 'models'
data_path: 'data/aclImdb_v1/aclImdb/'
batch_size: 32
seeds:  [3, 7, 42, 666]
word_embedding_sizes: [16,64,128]
learning_rates: [0.01, 0.001]