defaults:
  - models: TextCNN
  - override hydra/job_logging: disabled
  - _self_


n_epoch: 10
saving_path: 'models'
data_path: 'data/aclImdb_v1/aclImdb/'
batch_size: 64
seeds:  [3, 42]
word_embedding_sizes: [64, 128]
learning_rates: [0.001]
run_id: 0
